version: '3.8'

services:
  router:
    image: mongo
    container_name: mongo_router
    ports:
      - 27017:27017
    command: mongos --port 27017 --configdb "rs_config_server/config_server_1:27019,config_server_2:27019,config_server_3:27019" --bind_ip_all
    volumes:
      - ./scripts:/scripts
      - ../data:/data

  config_server_1:
    image: mongo
    container_name: mongo_config_1
    command: mongod --port 27019 --configsvr --replSet rs_config_server
    volumes:
      - ./scripts:/scripts

  config_server_2:
    image: mongo
    container_name: mongo_config_2
    command: mongod --port 27019 --configsvr --replSet rs_config_server
    volumes:
      - ./scripts:/scripts

  config_server_3:
    image: mongo
    container_name: mongo_config_3
    command: mongod --port 27019 --configsvr --replSet rs_config_server
    volumes:
      - ./scripts:/scripts

  shard1_1:
    image: mongo
    container_name: shard_1_node_1
    command: mongod --port 27018 --shardsvr --replSet rs_shard_1
    volumes:
      - ./scripts:/scripts

  shard1_2:
    image: mongo
    container_name: shard_1_node_2
    command: mongod --port 27018 --shardsvr --replSet rs_shard_1
    volumes:
      - ./scripts:/scripts

  shard1_3:
    image: mongo
    container_name: shard_1_node_3
    command: mongod --port 27018 --shardsvr --replSet rs_shard_1
    volumes:
      - ./scripts:/scripts

  shard2_1:
    image: mongo
    container_name: shard_2_node_1
    command: mongod --port 27020 --shardsvr --replSet rs_shard_2
    volumes:
      - ./scripts:/scripts

  shard2_2:
    image: mongo
    container_name: shard_2_node_2
    command: mongod --port 27020 --shardsvr --replSet rs_shard_2
    volumes:
      - ./scripts:/scripts

  shard2_3:
    image: mongo
    container_name: shard_2_node_3
    command: mongod --port 27020 --shardsvr --replSet rs_shard_2
    volumes:
      - ./scripts:/scripts

  shard3_1:
    image: mongo
    container_name: shard_3_node_1
    command: mongod --port 27021 --shardsvr --replSet rs_shard_3
    volumes:
      - ./scripts:/scripts

  shard3_2:
    image: mongo
    container_name: shard_3_node_2
    command: mongod --port 27021 --shardsvr --replSet rs_shard_3
    volumes:
      - ./scripts:/scripts

  shard3_3:
    image: mongo
    container_name: shard_3_node_3
    command: mongod --port 27021 --shardsvr --replSet rs_shard_3
    volumes:
      - ./scripts:/scripts
